/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8eb",
        "tertiary-container": "#a06900",
        "inverse-on-surface": "#eff1f4",
        "inverse-primary": "#a4c9ff",
        "on-primary-container": "#fdfcff",
        "surface-container-low": "#f2f4f7",
        "tertiary-fixed": "#ffddb4",
        "tertiary": "#7f5300",
        "on-background": "#191c1e",
        "surface-tint": "#0060ac",
        "outline": "#717783",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb953",
        "background": "#f7f9fc",
        "surface-container-highest": "#e0e3e6",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#291800",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#314867",
        "secondary-fixed-dim": "#b1c8ed",
        "surface-dim": "#d8dadd",
        "secondary": "#496080",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#004883",
        "primary-fixed": "#d4e3ff",
        "primary-container": "#2976c7",
        "on-tertiary-fixed-variant": "#633f00",
        "surface-container": "#eceef1",
        "surface": "#f7f9fc",
        "inverse-surface": "#2d3133",
        "secondary-container": "#c1d9fe",
        "outline-variant": "#c1c7d3",
        "on-secondary-fixed": "#001c39",
        "on-primary-fixed": "#001c39",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed": "#d4e3ff",
        "on-surface-variant": "#414751",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e0e3e6",
        "surface-bright": "#f7f9fc",
        "on-secondary-container": "#485e7e",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a4c9ff",
        "primary": "#005da7",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Lexend"],
        label: ["Lexend"]
      }
    },
  },
  plugins: [],
}
